repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
            -   id: check-yaml
                args:
                    - --unsafe
#            -   id: end-of-file-fixer
            -   id: trailing-whitespace
            -   id: check-added-large-files
    -   repo: https://github.com/charliermarsh/ruff-pre-commit
        rev: v0.4.5
        hooks:
            -   id: ruff
                args:
                    - --fix
            -   id: ruff-format
